apiVersion: v1
kind: Pod
metadata:
  name: vulnj-distroless
spec:
  containers:
  - name: vulnj-distroless
    image: tuxotron/vulnj:distroless
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: secret
      mountPath: "/etc/secret"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: mysecret